---
- hosts: DC
  sudo: yes
  tasks:
  - name: Install Apache Packages on RedHat Family 
    yum: name=httpd state=present
    when: ansible_os_family=="RedHat"

  - name: Install Apache Packages on Ubuntu Family 
    apt: name=apache2 state=present
    when: ansible_os_family=="Ubuntu"

  - name: Start Apache Service
    service: name=httpd state=started enabled=True

  - name: Deploy Site Files
    template: src=templates/index.j2 dest=/var/www/html/index.html
    notify:
      - amit

  - name: Force to Flush Handlers
    meta: flush_handlers


  - name: Install MariaDB Packages
    yum: name=mariadb-server state=present

  - name: Service MariaDB Start
    service: name=mariadb state=started


  - name: Deploy Site Nothing
    template: src=templates/abc.j2 dest=/var/www/html/abc.html
    notify:
      - nothing

  - name: Stop Firewall
    service: name=firewalld state=stopped enabled=False

  handlers:
  - name: amit
    service: name=httpd state=restarted
  - name: nothing
    service: name=httpd state=restarted
